add google_cloud_texttospeech package
jsk-ros-pkg/jsk_3rdparty pull request #218
Opened 2020-09-04 15:52 UTC by knorth55

add `google_cloud_texttospeech` package for ROS + `sound_play` + Google Cloud Text-to-Speech 

this package moves from [itohdak/audio_common@dev](https://github.com/itohdak/audio_common/tree/dev)

cc. @itohdak @iory @nakaotatsuya

2020-09-05 10:00 UTC, Naoki-Hiraoka requested changes

2020-09-05 10:09 UTC, Naoki-Hiraoka commented
I have confirmed that this PR works on my Ubuntu16 PC.

2020-09-05 13:48 UTC, knorth55 commented on 3rdparty/google_cloud_texttospeech/README.md
> +roslaunch google_cloud_texttospeech google_cloud_texttospeech.launch credentail:=/your/credentail/json/path
Thank you, I fix the typo.

2020-09-05 23:48 UTC, Naoki-Hiraoka approved these changes

2020-11-17 10:48 UTC, k-okada commented
@YoheiKakiuchi 課金はどのようにしていてるかREADMEかjskwikiかいてあるかな．
@nakaotatsuya @iory HSR/Aeroがこれを使っているという事ですがが，.rosinstallはどこにあるかな？

2020-11-17 11:05 UTC, merged

2020-11-17 11:48 UTC, iory commented
HSRは標準の音声合成があるのでこちらは使ってないです。
@ Unimendacity aeroで昔使っていたと思うけど分かるかな？

2020-11-17 13:23 UTC, knorth55 commented
@iory なるほど、HSRはそっか
そっちの部屋だとAeroがこれを使ってるのか
Aeroのrosinstallはどこにありますか？

@k-kimura HRP2はいまGoogleで話しているんでしょうか？

2020-11-17 15:25 UTC, iory commented
> そっちの部屋だとAeroがこれを使ってるのか
> Aeroのrosinstallはどこにありますか？

@Unimendacity 
これ分かるかな？

2020-11-17 15:30 UTC, k-kimura commented
> HRP2はいまGoogleで話しているんでしょうか？

hrp2007はsound_play単体です．

2020-11-17 15:57 UTC, knorth55 commented
@k-kimura origin/masterのsound_play単体では日本語は話すことはないのですが，HRP2007は日本語は話さないのでしょうか？それとも伊藤くんのブランチでやっていますか？もしもそのブランチでやってらっしゃるなら，こちらに切り替えてもらえると，audio_commonを伊藤くんブランチを使うひつようがなくなります．

2020-11-17 16:25 UTC, k-kimura commented
hrp2007は日本語喋ってないですね．
vのsound_playはdev-on-indigo-develというブランチ（伊藤くんのブランチ）になってますが，
引き継ぎのときにpythonのバージョンまわりで現状維持を選択して
結局GoogleCloudのapiは諦めて，デフォルトのsound_playを使ってました．

> こちらに切り替えてもらえると，audio_commonを伊藤くんブランチを使うひつようがなくなります．

なるほど，今後Googleのを使ってく場合はmasterのままで使えるようになったということですね．

2020-11-17 16:34 UTC, knorth55 commented
@k-kimura 
ありがとうございます．
いちおう`package.xml`にも書いてありますが，`google-cloud-texttospeech=<1.0.1`でpythonのバージョン周りは`python2.7`なら解決するかと思います．
そして，日本語用のsoundplayをこんな感じで書くと，伊藤くんがやってくれたのと同じように日本語を話すようになります．
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/3rdparty/google_cloud_texttospeech/launch/google_cloud_texttospeech.launch#L35-L48

ちなみにですがhrp2のvのrosinstallとかってどこかのレポジトリで管理していますか？

2020-11-17 16:37 UTC, knorth55 commented
@k-kimura 
あと`audio_common`は伊藤くんのPRをマージしてリリースしているので，ソースで入れる必要はもうないかと思います．
https://github.com/ros-drivers/audio_common/pull/126

2020-11-17 16:51 UTC, k-kimura commented
> ちなみにですがhrp2のvのrosinstallとかってどこかのレポジトリで管理していますか？

少なくともhrp2007vのrosinstallはどこにも管理されてないとおもう．

2020-11-18 10:34 UTC, Unimendacity commented
> > そっちの部屋だとAeroがこれを使ってるのか
> > Aeroのrosinstallはどこにありますか？
> 
> @Unimendacity
> これ分かるかな？

返信遅れてすみませんでした.
AeroがGoogleで話しています.
Aeroのrosinstallはhttps://github.com/taichiH/jsk_robot/tree/master/jsk_aero_robot/jsk_aero_startup/scriptsにあります.
解決してよかったと思います.

2020-11-18 11:15 UTC, knorth55 commented
@Unimendacity 

ありがとうございます．text2waveがそのまま置かれていますね．
これをこちらのgoogle_cloud_texttospeechのtext2waveに置き換えることができます
https://github.com/taichiH/jsk_robot/blob/master/jsk_aero_robot/jsk_aero_startup/scripts/text2wave

cc. @taichiH