[WIP]Add DialogFlow https webhook server
jsk-ros-pkg/jsk_3rdparty pull request #242
Opened 2021-04-27 06:52 UTC by mqcmd196

This PR is for getting https POST responses from DialogFlow webhook. If you use this, you can execute app_manager apps from Google Home, Google Chat, Line, Slack, etc...

### ToDo
#### Document
- [ ] Make README
- [ ] Make DialogFlow Manual
- [ ] Make demo video
#### Coding
- [ ] Make the correct POST response defined at [here](https://cloud.google.com/dialogflow/es/docs/fulfillment-webhook?hl=ja#webhook_response )

2021-06-03 05:10 UTC, mqcmd196 commented
It's ready for reviewing

2021-06-03 05:27 UTC, knorth55 requested changes

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/README.md
> +  "keyfile": "/var/lib/robot/dialogflow/webhook/server.key"
```suggestion
  "port": 8090,
  "certfile": "/path/to/your/server.crt",
  "keyfile": "/path/to/your/server.key",
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/README.md
> +DOMAIN='dialogflow.yourdomain.com' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem > /var/lib/robot/dialogflow/webhook/server.pem'
```suggestion
DOMAIN='dialogflow.yourdomain.com' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem > /path/to/your/server.pem'
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/README.md
> +DOMAIN='dialogflow.yourdomain.com' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/privkey.pem > /var/lib/robot/dialogflow/webhook/server.key'
```suggestion
DOMAIN='dialogflow.yourdomain.com' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/privkey.pem > /path/to/your/server.key'
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/README.md
> +sudo chmod -R go-rwx /var/lib/robot/dialogflow/webhook/
```suggestion
sudo chmod go-rwx /path/to/your/server.key
sudo chmod go-rwx /path/to/your/server.crt
sudo chmod go-rwx /path/to/your/server.pem
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +        conffile = rospack.get_path('dialogflow_task_executive') + "/config/webhook.json"
can you change this to rosparam and set it from launch?

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +class Server():
```suggestion
class Server(object):
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +        conffile = rospack.get_path('dialogflow_task_executive') + "/config/webhook.json"
```
conffile = rospy.get_param('~config_json', os.path.join(rospack.get_path('dialogflow_task_executive'), 'config/webhook.json')
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/launch/webhook_server.launch
> +  <node name="dialogflow_https_server" pkg="dialogflow_task_executive" type="webhook_server.py" />
```suggestion
  <arg name="config_json" default="$(find dialogflow_task_executive)/config/webhook.json" />
  <node name="dialogflow_https_server" pkg="dialogflow_task_executive" type="webhook_server.py">
    <rosparam subst_value="true">
      config_json: $(arg config_json)
    </rosparam>
  </node>
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +    except Exception as e:
why do we need to catch the exception?

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +    except Exception as e:
if you want to catch the exception and try multiple times, please add trial loop

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/node_scripts/webhook_server.py
> +#!/usr/bin/env python3
```suggestion
#!/usr/bin/env python
```

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/.gitignore
> +/config/webhook.json
remove this .gitignore file

2021-06-03 05:27 UTC, knorth55 commented on dialogflow_task_executive/README.md
> +Your server's host name, port, certfile and keyfile should be passed to the node. You have to write `dialogflow_task_executive/config/webhook.json`, like
```suggestion
Your server's host name, port, certfile and keyfile should be passed to the node.  The example config json is as follows:
```

2021-06-03 07:33 UTC, mqcmd196 commented
@knorth55 Thanks, I fixed and confirmed it works in the robot.

2021-06-03 09:20 UTC, knorth55 approved these changes

2021-06-03 09:22 UTC, knorth55 commented
can you check this comment? https://github.com/knorth55/jsk_robot/pull/113#discussion_r644633019
@mqcmd196

2021-06-03 10:37 UTC, knorth55 approved these changes

2021-06-04 09:11 UTC, knorth55 commented
Good work! LGTM.
This PR passed all tests!

2021-06-09 23:12 UTC, k-okada reviewed
waiting for video ;-)

2021-12-21 04:47 UTC, mqcmd196 commented
I'm sorry for being sooooooo late, I forgot adding the video and I did it.

2021-12-28 07:08 UTC, mqcmd196 commented
Please wait for https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/290 's commit.

2022-01-18 05:47 UTC, mqcmd196 commented
close and separate package

2022-01-18 05:47 UTC, closed without merging