Add webrtcvad_ros package for Voice Activity Detection
jsk-ros-pkg/jsk_3rdparty pull request #258
Opened 2021-06-03 08:54 UTC by sktometometo

Add webrtcvad_ros package for Voice Activity Detection.
This package provides a wrapper node for [webrtcvad](https://github.com/wiseman/py-webrtcvad) which is for Voice Activity Detection.
It subscribes an audio topic and publish a flag if curretly speeched or not with VAD.

## Prerequities

```bash
pip install webrtcvad
```

## Example

You need a microphone on your computer to use this example.

```bash
roslaunch webrtcvad_ros sample.launch
```

2021-06-09 23:22 UTC, k-okada requested changes
please use `<exec_depend>python-webrtcvad-pip</exec_depend>` instead of ask user to manually install `pip install webrtcad` 
from https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L5467, 
https://github.com/ros/rosdistro/pull/20438 . It seems people from Fraunhofer IPA or https://github.com/mojin-robotics?type=source ?
It seems they start company to sell CoB robot. I think it worth to check.

2021-06-09 23:27 UTC, k-okada commented on webrtcvad_ros/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
please set `cmake_minimum_required(VERSION 2.8.3)` as other packages
```
_______________________________________________________________________________
  Errors << webrtcvad_ros:cmake /github/home/ros/ws_jsk_3rdparty/logs/webrtcvad_ros/build.cmake.000.log
  CMake Error at /github/home/ros/ws_jsk_3rdparty/src/jsk_3rdparty/webrtcvad_ros/CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.0.2 or higher is required.  You are running version 2.8.12.2
  
 ```

2021-06-10 04:49 UTC, sktometometo commented on webrtcvad_ros/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
fixed.

2021-06-10 22:03 UTC, sktometometo commented
Fixed

2021-06-10 22:04 UTC, sktometometo commented
Some tests still fails. Working on it now

2021-06-11 08:46 UTC, sktometometo commented
Seems fixed

2021-06-11 09:09 UTC, k-okada requested changes
can you add video? to show the example? like https://github.com/jsk-ros-pkg/jsk_common/pull/1681 ?

2021-08-25 07:04 UTC, sktometometo commented
Moved to https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/282

2021-08-25 07:04 UTC, closed without merging