add ROS interface for https://cloud.google.com/natural-language
jsk-ros-pkg/jsk_3rdparty pull request #304
Opened 2021-12-20 09:41 UTC by k-okada

1. @MiyabiTane 時間があるときでいいので，README見て使ってみてフィードバックください．例題「吾輩は猫である．．．」がイマイチなので良い例があるとよいです

2. @mqcmd196 @708yamaguchi @sktometometo Google Key は共有のは無いんだっけ ros_speech_recognition では何か使っているはずなんだけど．．．すでにあれば，それに切り替えます．

2021-12-20 09:48 UTC, sktometometo commented
@k-okada FetchやSpotで利用しているGoogle Cloudのサービスは dialogflow@jsk.imi.i.u-tokyo.ac.jp アカウントで各自が特定の目的用のサービスアカウントとkeyを作っている状態です。

2021-12-20 11:13 UTC, mqcmd196 commented
@sktometometo ロボットごとのDialogflowアカウントを作ると，それごとのGoogle Cloudプロジェクト(?)が同時に生成されるようになっていて，そのプロジェクトページで色々APIを有効にしていくのが管理しやすいのかなと思います．(GoogleChatROS と Dialogflowはそうしています)

2021-12-20 11:16 UTC, mqcmd196 commented
例えばこんな感じですhttps://console.cloud.google.com/home/dashboard?project=spot-jsk-xc9u

2021-12-20 11:26 UTC, mqcmd196 commented
JSK DialogFlowアカウントの https://console.cloud.google.com/ を見ると，多分現状はそうなっているので大丈夫で，ただこのKeyは何かサービスごとに色んな人が作っているっぽくて，一つのロボットでもいろいろなキーがいろんなサービスごとに分散してしまっていそうですね．理想的な運用としては一つのKeyを発行したときに，そのKeyに対して様々なAPI利用権限を付与する，というのが正しそうです．

2021-12-20 11:37 UTC, mqcmd196 commented
で，本題の

> Google Key は共有のは無いんだっけ ros_speech_recognition では何か使っているはずなんだけど．．．すでにあれば，それに切り替えます．

ですが，本PR用にChatだけのAPIを作るか，それとも `ros_speech_recognition` に付与して，同じAPIキーで使えるようにする，かによると思います．

2021-12-21 05:16 UTC, mqcmd196 commented
@k-okada 作りました．https://drive.google.com/drive/folders/1Enbbta5QuZ-hrUWdTjVDEjDJc3j7Abxo?usp=sharing

2021-12-21 05:22 UTC, mqcmd196 commented
@MiyabiTane どのロボットで使う予定がありますか？

2021-12-21 05:29 UTC, MiyabiTane commented
岡田先生、実装ありがとうございました。後でデモ内容を追加させて頂きます。
@mqcmd196 PR2で使う予定です、ありがとうございます。

2021-12-21 05:37 UTC, mqcmd196 commented
@MiyabiTane 作りました https://drive.google.com/drive/folders/1Enbbta5QuZ-hrUWdTjVDEjDJc3j7Abxo?usp=sharing

2021-12-21 07:27 UTC, k-okada commented
> JSK的らくらく運用としては一つのキーに使いたい全APIの運用を許可する，という認識です．(後者はセキュリティとか課金的に大変そうだから公式では非推奨??)

で良いとおもいます．誰が使っているかわからない大量課金とか，ここからセキュリティが破られて，なにか問題がある，とかあればまた考えましょう．

ロボットの体内鍵は，現状動いていれば今のままで良くて，ロボットをちゃんと管理している人がいる間はその人がファイルをつくって体内のlaunchファイルに入れるんだとおもいますが，体内のPCのバージョンアップとか，ロボットが２台３台と増える，となるとまた面倒になるので，らくらく運用に収斂することになるとおもいます．
一般ユーザは気にすること無く，普通にROSサービスを叩けば良いんので管理者だけの問題かとおもいます．

@mqcmd196 共通鍵にChatbotAPIの権限を付与したつもりなので，これで動くか確認してください．また，サンプルプログラムのデフォルトキーをこれにしておいてください．

2021-12-21 09:29 UTC, MiyabiTane commented
@k-okada chaplus
エージェントの返答を感情分析するようなデモを作ってみました。
以下、会話の例です。
https://gist.github.com/MiyabiTane/d1d806279d129fde5a25d1ce9018057f

pushしてPRしようとしたのですが、以下のようなエラーが出て、pushできず、権限の問題などがあるのでしょうか？Access Tokenは発行済で、他のレポジトリではpushできています（お手数おかけしてすみません）
Forkして使っているのですが、originはMiyabiTaneになっています
```
tork@ubuntu:~/ros/jsk_pr2_ws/src/jsk_3rdparty$ git push origin google_nlp_chat Username for 'https://github.com': MiyabiTane
Password for 'https://MiyabiTane@github.com': 
Counting objects: 29, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (29/29), 6.39 KiB | 6.39 MiB/s, done.
Total 29 (delta 9), reused 19 (delta 4)
remote: Resolving deltas: 100% (9/9), completed with 3 local objects.
To https://github.com/MiyabiTane/jsk_3rdparty
 ! [remote rejected]   google_nlp_chat -> google_nlp_chat (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/indigo.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/MiyabiTane/jsk_3rdparty'
```

2021-12-21 09:40 UTC, k-okada commented
@MiyabiTane Tokenの発行時にworkflowにもチェックが必要かな．．． https://qiita.com/kter/items/84f3ece9a41a2bec535f

https://gist.github.com/MiyabiTane/d1d806279d129fde5a25d1ce9018057f
は面白いね．これでやりたいことが出来ている感じなのかな？
細かいところだと，文全体のsentimentではなくて，単語？節？のsentiment も出せそうなんだけど，どっちがいいんだろうとか，両方必要なのかな，とかおもいました．
https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/analyzeEntitySentiment

2021-12-21 09:51 UTC, MiyabiTane commented
@k-okada pushできましたありがとうございます。私側の設定の問題で申し訳ないです...。

[この例](https://gist.github.com/MiyabiTane/d1d806279d129fde5a25d1ce9018057f)のように、飾り付けしながら雑談をして、ロボットの返答の感情分析結果を表情に反映できたら良いなと考えていました。

もう一つやりたいこととしては、（調べたところdialogflowでは実現できていることだと思いますが）、人が「風船をもっと右に置いてほしい」といった提案をした時に言い方が多少違くとも汲み取ってほしくて、そのあたりもこのAPIの構文解析結果が使えたら良いのかなと思いました。

ロボットの返答文はそこまで長くないので、今のところ文全体のsentimentで考えています。

2022-04-04 01:54 UTC, mqcmd196 requested changes

2022-04-04 01:54 UTC, mqcmd196 commented on ros_google_cloud_language/README.md
> +ros_google_cloud_language
I prefer to use full-service-name in package name, like `ros_google_natural_language`

2022-04-04 01:54 UTC, mqcmd196 commented on ros_google_cloud_language/README.md
> +roslaunch demo.launch google_cloud_credentials_json:=${HOME}/Downloads/eternal-byte-236613-4bc6962824d1.json
`roslaunch ros_google_cloud_language demo.launch`

2022-04-04 01:54 UTC, mqcmd196 commented on ros_google_cloud_language/node_scripts/analyze_text.py
> +            # # Analayze Syntax
Is this in development?

2022-04-04 01:54 UTC, mqcmd196 commented on ros_google_cloud_language/node_scripts/analyze_text.py
> +#!/usr/bin/env python
Do we need shebang while using catkin_virtualenv?? Could you give me advice @knorth55 ...?

2022-10-31 07:54 UTC, MiyabiTane commented
構文解析の結果も使いたいなと思い、追加しました。
https://github.com/k-okada/jsk_3rdparty/pull/9

2022-11-02 11:47 UTC, k-okada commented
@mqcmd196 から
> I prefer to use full-service-name in package name, like ros_google_cloud_natural_language

という提案がでていて，層かな，とも思うけど，イポプで，`google_chat_ros` という名前もあったりして，ルールも曖昧なのと，すでに利用者もいるので，このままマージで良いと思いますが，どうでしょうか．

2022-11-02 23:33 UTC, mqcmd196 commented
はい、ユーザが多いのでマージでOKだと思います

2022-11-04 01:24 UTC, merged