[API Change] use project_id from json, instead of credentials
jsk-ros-pkg/jsk_3rdparty pull request #460
Opened 2023-04-25 11:55 UTC by k-okada

if we have google credential file
```
{
  "type": "service_account",
  "project_id": "foo",
...
}
```
and use launch file such as
```
  <include file="$(find dialogflow_task_executive)/launch/dialogflow_ros.launch">
    <arg name="credential" value="$(arg google_credentials_json)" />
    <arg name="project_id" value="bar" />
</launch>
```
it still uses `foo` project.

This PR override credential setting and use `project_id` from rosparam.

This PR changes existing launch files that wrongly set `project_id` in launch file, which was ignored, will be effective.

2023-04-28 04:07 UTC, mqcmd196 commented
I can hardly imagine when the situation
> if we have google credential file
> 
> {
>   "type": "service_account",
>   "project_id": "foo",
> ...
> }
> and use launch file such as
> 
>   <include file="$(find dialogflow_task_executive)/launch/dialogflow_ros.launch">
>     <arg name="credential" value="$(arg google_credentials_json)" />
>     <arg name="project_id" value="bar" />
> </launch>
> it still uses foo project.
occurs. Does someone want to change `project_id` after the credential file from GCP has been generated?

2023-04-28 04:08 UTC, mqcmd196 requested changes

2023-04-28 04:08 UTC, mqcmd196 commented on dialogflow_task_executive/node_scripts/dialogflow_client.py
> +                rospy.logwarn("overridd project_id")
typo
overridd -> override

2023-04-28 09:19 UTC, k-okada commented on dialogflow_task_executive/node_scripts/dialogflow_client.py
> +                rospy.logwarn("overridd project_id")
thank you.

2023-04-28 09:21 UTC, k-okada commented
having multiple credential files is too complex for new useres, for example https://github.com/jsk-ros-pkg/jsk_robot/pull/1792 uses one file for chat, NLP and dialogflow. 
BTW, Can we share credential file over different agent ?

2023-04-29 07:19 UTC, mqcmd196 commented
> having multiple credential files is too complex for new useres, for example https://github.com/jsk-ros-pkg/jsk_robot/pull/1792 uses one file for chat, NLP and dialogflow.

I see. 

> BTW, Can we share credential file over different agent ?

Do you mean that we generate 2 dialogflow agents and share keys between them? I think we can't do that. When we create dialogflow agent, dialogflow creates another GCP project.

2023-06-07 04:31 UTC, k-okada commented
@mqcmd196 I think we can. Here, we have two agents, collaborative remembering and facial expression, 
![Screenshot from 2023-06-07 13-25-50](https://github.com/jsk-ros-pkg/jsk_3rdparty/assets/493276/cb4ee7cd-22c7-43ca-941f-c3891dc08f24)

![Screenshot from 2023-06-07 12-03-49](https://github.com/jsk-ros-pkg/jsk_3rdparty/assets/493276/ebf473be-513f-4704-b0fd-e7ff67601626)

and both projects have granted permissions to eternal-byte IAM, so in this example (
https://github.com/jsk-ros-pkg/jsk_robot/pull/1792/files#diff-1b50ec7cff80b4d692c0044c454c168b226ff9011d2e7faed4a48cfcdb87b5b3R9 ) user has  access to both collaborative remoembering and facial expression

2023-06-07 04:31 UTC, merged